name: email
on: [ push ]
jobs:
  Email notification:
    runs-on: windows-latest
    steps:
      -name- send email using gmail 
         uses: dawidd6/action-send-mail@v2
         with:
           server_address: smtp.gmail.com
           server_port: 465
  
           username: ${{ secrets.EMAIL_USERNAME }}
           password: ${{ secrets.EMAIL_PASSWORD }}
  #
           subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
  
           body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
   
           to: nileshkr1112@gmail.com

           from: Nilesh kumar
