# This workflow will install Python dependencies, run tecsts and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/us ing-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      
    #- name: Install dependencies
     # run: python install twine
     
  Regex_Check:
   runs-on: windows-latest
   steps:
    # - uses:  actions/checkout@v3
     - name:  Regex check
       run: |
         python regex.py
         shell: py
         
 
   
     
        
