name: Build

on:  push

env:
  RUN_NUMBER:  ${{ github.run_number }}
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: ENV1 CHECK 
        run:  |
         mkdir${{github.worplace}}/../..nucdelete
         dir

      - name: ENV1 CHECK 
        run: echo "${{  env.RUN_NUMBER  }}"
        
          #echo Hello, world!
          #echo ${{ GITHUB_RUN_NUMBER  }}
          #echo ${{ GITHUB_REPOSITORY  }}
        
  
      #- name: Get Git Log
       # id: git_log
       # uses: JantHsueh/get-git-log-action@master
          
     # - name: email check
      #  uses: actions/checkout@v2

      - name: Dir check 
        run: dir
      - name: email check 
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          to: nileshkr1112@gmail.com
          from: Nilesh kumar
          attachments: D:\a\monitoring-test-\monitoring-test-\test.json
            #- filename: 'text1.json'
             # path: 'https://raw.github.com/nodemailer/nodemailer/master/LICENSE'
   
        
    
    
